/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package venta;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class registro_ventas extends javax.swing.JFrame {

    /**
     * Creates new form registro_ventas
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public registro_ventas() {
        initComponents();
        this.setLocationRelativeTo(null);
        String ids[] = {"Nombre", "DNI", "Telefono", "Producto", "Marca", "N° de unidades"};
        modelo.setColumnIdentifiers(ids);
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnGENERAR_PEDIDO = new javax.swing.JButton();
        jbtnELIMINAR_FILA = new javax.swing.JButton();
        jbtnELIMINAR_TODO = new javax.swing.JButton();
        jtxtNOMBRE = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtxtTELEFONO = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtDNI = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jcbxPRODUCTO = new javax.swing.JComboBox<>();
        jtxtUNIDADES = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tabla = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnAGREGAR_PEDIDO = new javax.swing.JButton();
        jbtnSALIR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaBOLETA_EMISION = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 620));

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 123, 255));
        jPanel3.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Fax", 3, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("IMPORTADORA EXPRESS");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 0, 480, 70);

        jLabel3.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 100, 80, 30);

        jLabel4.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel4.setText("Telefono");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 140, 80, 30);

        jLabel5.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel5.setText("DNI");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 180, 80, 30);

        jLabel6.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel6.setText("Producto");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 220, 80, 30);

        jLabel2.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel2.setText("N° de unidades");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 260, 130, 30);

        jbtnGENERAR_PEDIDO.setBackground(new java.awt.Color(0, 123, 255));
        jbtnGENERAR_PEDIDO.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnGENERAR_PEDIDO.setForeground(new java.awt.Color(0, 0, 0));
        jbtnGENERAR_PEDIDO.setText("Generar pedido");
        jbtnGENERAR_PEDIDO.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnGENERAR_PEDIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGENERAR_PEDIDOActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGENERAR_PEDIDO);
        jbtnGENERAR_PEDIDO.setBounds(130, 500, 150, 40);

        jbtnELIMINAR_FILA.setBackground(new java.awt.Color(0, 123, 255));
        jbtnELIMINAR_FILA.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnELIMINAR_FILA.setForeground(new java.awt.Color(0, 0, 0));
        jbtnELIMINAR_FILA.setText("Eliminar fila");
        jbtnELIMINAR_FILA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnELIMINAR_FILA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnELIMINAR_FILAActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnELIMINAR_FILA);
        jbtnELIMINAR_FILA.setBounds(240, 300, 150, 40);

        jbtnELIMINAR_TODO.setBackground(new java.awt.Color(0, 123, 255));
        jbtnELIMINAR_TODO.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnELIMINAR_TODO.setForeground(new java.awt.Color(0, 0, 0));
        jbtnELIMINAR_TODO.setText("Eliminar todo");
        jbtnELIMINAR_TODO.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnELIMINAR_TODO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnELIMINAR_TODOActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnELIMINAR_TODO);
        jbtnELIMINAR_TODO.setBounds(440, 300, 150, 40);

        jtxtNOMBRE.setBackground(new java.awt.Color(0, 123, 255));
        jtxtNOMBRE.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jtxtNOMBRE.setForeground(new java.awt.Color(0, 0, 0));
        jtxtNOMBRE.setBorder(null);
        jtxtNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNOMBREActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtNOMBRE);
        jtxtNOMBRE.setBounds(170, 90, 240, 30);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(170, 120, 240, 10);

        jtxtTELEFONO.setBackground(new java.awt.Color(0, 123, 255));
        jtxtTELEFONO.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jtxtTELEFONO.setForeground(new java.awt.Color(0, 0, 0));
        jtxtTELEFONO.setBorder(null);
        jPanel3.add(jtxtTELEFONO);
        jtxtTELEFONO.setBounds(170, 130, 240, 30);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(170, 160, 240, 10);

        jtxtDNI.setBackground(new java.awt.Color(0, 123, 255));
        jtxtDNI.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jtxtDNI.setForeground(new java.awt.Color(0, 0, 0));
        jtxtDNI.setBorder(null);
        jPanel3.add(jtxtDNI);
        jtxtDNI.setBounds(170, 170, 240, 30);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(170, 200, 240, 10);

        jcbxPRODUCTO.setBackground(new java.awt.Color(0, 123, 255));
        jcbxPRODUCTO.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jcbxPRODUCTO.setForeground(new java.awt.Color(0, 0, 0));
        jcbxPRODUCTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pantalon", "Polos", "Buzos", "Poleras", "Casacas" }));
        jPanel3.add(jcbxPRODUCTO);
        jcbxPRODUCTO.setBounds(170, 220, 240, 30);

        jtxtUNIDADES.setBackground(new java.awt.Color(0, 123, 255));
        jtxtUNIDADES.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jtxtUNIDADES.setForeground(new java.awt.Color(0, 0, 0));
        jtxtUNIDADES.setBorder(null);
        jPanel3.add(jtxtUNIDADES);
        jtxtUNIDADES.setBounds(170, 250, 240, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(170, 280, 240, 10);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta/registro-en-linea (1).png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(420, 40, 260, 256);

        jTable1.setBackground(new java.awt.Color(0, 123, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setViewportView(jTable1);

        jPanel3.add(tabla);
        tabla.setBounds(10, 350, 660, 140);

        jbtnAGREGAR_PEDIDO.setBackground(new java.awt.Color(0, 123, 255));
        jbtnAGREGAR_PEDIDO.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnAGREGAR_PEDIDO.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAGREGAR_PEDIDO.setText("Agregar pedido");
        jbtnAGREGAR_PEDIDO.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnAGREGAR_PEDIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAGREGAR_PEDIDOActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAGREGAR_PEDIDO);
        jbtnAGREGAR_PEDIDO.setBounds(40, 300, 150, 40);

        jbtnSALIR.setBackground(new java.awt.Color(0, 123, 255));
        jbtnSALIR.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnSALIR.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSALIR.setText("Salir");
        jbtnSALIR.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSALIRActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSALIR);
        jbtnSALIR.setBounds(380, 500, 150, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registro de venta", jPanel1);

        jPanel2.setLayout(null);

        jtxaBOLETA_EMISION.setColumns(20);
        jtxaBOLETA_EMISION.setRows(5);
        jtxaBOLETA_EMISION.setText("\t\t         IMPORTADORA EXPRESS");
        jScrollPane1.setViewportView(jtxaBOLETA_EMISION);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 30, 600, 350);

        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton1.setText("Generar Boleta");
        jPanel2.add(jButton1);
        jButton1.setBounds(70, 400, 170, 50);

        jTabbedPane1.addTab("Boletas de emision", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGENERAR_PEDIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGENERAR_PEDIDOActionPerformed
        // TODO add your handling code here:
        String nombre = jtxtNOMBRE.getText();
        int DNI = Integer.parseInt(jtxtDNI.getText());
        int telefono = Integer.parseInt(jtxtTELEFONO.getText());
        int unidades = Integer.parseInt(jtxtUNIDADES.getText());
        String nombre_producto = jcbxPRODUCTO.getSelectedItem().toString();
        clases.producto p = new clases.producto(telefono, nombre_producto, DNI, unidades, nombre);
        clases.cliente c = new clases.cliente(nombre, DNI, telefono);
        jtxaBOLETA_EMISION.append("Nombre del cliente:" + nombre);
        jtxaBOLETA_EMISION.append("DNI:" + DNI);
        jtxaBOLETA_EMISION.append("Telefono: " + telefono);


    }//GEN-LAST:event_jbtnGENERAR_PEDIDOActionPerformed

    private void jbtnELIMINAR_FILAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnELIMINAR_FILAActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            modelo.removeRow(jTable1.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione la fila a eliminar");
        }
    }//GEN-LAST:event_jbtnELIMINAR_FILAActionPerformed

    private void jbtnELIMINAR_TODOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnELIMINAR_TODOActionPerformed
        int cant = jTable1.getRowCount();
        for (int i = cant - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_jbtnELIMINAR_TODOActionPerformed

    private void jtxtNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNOMBREActionPerformed

    private void jbtnAGREGAR_PEDIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAGREGAR_PEDIDOActionPerformed
        // TODO add your handling code here:
        String confirmacion;
        String nombre = jtxtNOMBRE.getText();
        int DNI = Integer.valueOf(jtxtDNI.getText());
        int telefono = Integer.valueOf(jtxtTELEFONO.getText());
        int unidades = Integer.valueOf(jtxtUNIDADES.getText());
        String nombre_producto = jcbxPRODUCTO.getSelectedItem().toString();
        clases.producto p = new clases.producto(telefono, nombre_producto, DNI, unidades, nombre);
        clases.cliente c = new clases.cliente(nombre, DNI, telefono);
        modelo.addRow(new Object[]{nombre, DNI, telefono, nombre_producto, p.getMarca(), unidades});
        confirmacion = JOptionPane.showInputDialog("¿Desea mantener al mismo cliente?\n"
                + "-Si\n"
                + "-No");
        if (confirmacion.equals("si") || confirmacion.equals("Si")) {
            jtxtNOMBRE.setText(nombre);
            jtxtTELEFONO.setText("" + c.getTelefono());
            jtxtDNI.setText("" + c.getDNI());
            jcbxPRODUCTO.setSelectedItem(nombre_producto);
            jtxtUNIDADES.setText("");
        } else if (confirmacion.equals("No") || confirmacion.equals("no")) {
            jtxtTELEFONO.setText("");
            jtxtDNI.setText("");
            jcbxPRODUCTO.setSelectedItem(nombre_producto);
            jtxtNOMBRE.setText("");
            jtxtUNIDADES.setText("");
        }
    }//GEN-LAST:event_jbtnAGREGAR_PEDIDOActionPerformed

    private void jbtnSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAGREGAR_PEDIDO;
    private javax.swing.JButton jbtnELIMINAR_FILA;
    private javax.swing.JButton jbtnELIMINAR_TODO;
    private javax.swing.JButton jbtnGENERAR_PEDIDO;
    private javax.swing.JButton jbtnSALIR;
    private javax.swing.JComboBox<String> jcbxPRODUCTO;
    private javax.swing.JTextArea jtxaBOLETA_EMISION;
    private javax.swing.JTextField jtxtDNI;
    private javax.swing.JTextField jtxtNOMBRE;
    private javax.swing.JTextField jtxtTELEFONO;
    private javax.swing.JTextField jtxtUNIDADES;
    private javax.swing.JScrollPane tabla;
    // End of variables declaration//GEN-END:variables
}
