/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recuperar_contraseña;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class contraseña_recuperar extends javax.swing.JFrame {

    /**
     * Creates new form recuperar_contraseña
     */
    public contraseña_recuperar() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel4, "src/recuperar_contraseña/olvidar_contraseña.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUSUARIO = new javax.swing.JTextField();
        jtxtCORREO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnREGRESAR = new javax.swing.JButton();
        jbtnRECUPERAR_CONTRASEÑA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(535, 282));

        jPanel1.setMinimumSize(new java.awt.Dimension(517, 261));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese su usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 140, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese su correo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 140, 30);
        jPanel1.add(jtxtUSUARIO);
        jtxtUSUARIO.setBounds(160, 80, 200, 30);

        jtxtCORREO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCORREOActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCORREO);
        jtxtCORREO.setBounds(160, 130, 200, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel3.setText("Complete todos los campos");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 280, 40);

        jbtnREGRESAR.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jbtnREGRESAR.setText("Regresar");
        jbtnREGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnREGRESARActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnREGRESAR);
        jbtnREGRESAR.setBounds(60, 200, 140, 40);

        jbtnRECUPERAR_CONTRASEÑA.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnRECUPERAR_CONTRASEÑA.setText("Recuperar contraseña");
        jbtnRECUPERAR_CONTRASEÑA.setActionCommand("Recuperar \ncontraseña");
        jbtnRECUPERAR_CONTRASEÑA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRECUPERAR_CONTRASEÑAActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRECUPERAR_CONTRASEÑA);
        jbtnRECUPERAR_CONTRASEÑA.setBounds(220, 200, 220, 40);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 30, 100, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jtxtCORREOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCORREOActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtCORREOActionPerformed

    private void jbtnREGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnREGRESARActionPerformed
        // TODO add your handling code here:
        login.login inicio = new login.login();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnREGRESARActionPerformed

    private void jbtnRECUPERAR_CONTRASEÑAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRECUPERAR_CONTRASEÑAActionPerformed
        // TODO add your handling code here:
        String correo = jtxtCORREO.getText();
        String usuario = jtxtUSUARIO.getText();
        clases.vendedor ven = new clases.vendedor(correo, ERROR, HAND_CURSOR, ERROR, usuario, correo, correo, ERROR, WIDTH, WIDTH, correo, ERROR, WIDTH, usuario);
        if (ven.getUsuario().contains(usuario) && ven.getCorreo().equals(correo)) {
            JOptionPane.showMessageDialog(null, "Su cotraseña es: " + ven.getContraseña());
            login.login inicio = new login.login();
            inicio.setVisible(true);
            this.dispose();
        } else if(correo.equals("")|| usuario.equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese todos sus datos primero");
        }else{
            JOptionPane.showMessageDialog(null, "Datos invalidos");
        }

    }//GEN-LAST:event_jbtnRECUPERAR_CONTRASEÑAActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnRECUPERAR_CONTRASEÑA;
    private javax.swing.JButton jbtnREGRESAR;
    private javax.swing.JTextField jtxtCORREO;
    private javax.swing.JTextField jtxtUSUARIO;
    // End of variables declaration//GEN-END:variables
}
